version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: dataspace_internal_postgres
    environment:
      POSTGRES_DB: dataspace
      POSTGRES_USER: dataspace
      POSTGRES_PASSWORD: ds!123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:16.1
    container_name: dataspace_test_db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234!
    ports:
      - "5433:5432"
volumes:
  postgres_data:
